server:
  port: 8081
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vibemusic?useUnicode=true&characterEncoding=utf-8&useSSL=false # 修改你的 MySQL 地址和库名
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource # 配置连接池
  # Redis服务连接配置
  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      password:
  servlet:
    multipart:
      max-file-size: 100MB # 设置最大上传文件大小为100MB
      max-request-size: 1024MB # 设置最大请求大小为1024MB

  # 配置邮件服务
  mail:
    host: smtp.qq.com
    port: 587
    username: 3095438615@qq.com
    password: kaodyhhprkrfdeaf   # QQ 邮箱授权码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        # debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          # 邮件服务超时时间配置
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


# 配置 mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
    map-underscore-to-camel-case: true # 类属性与表字段的驼峰映射
  global-config:
    db-config: # 数据库配置
      table-prefix: tb_  # 表名前缀为tb_，表名为前缀连接类名（小写）

jwt:
  secret_key: "VIBE_MUSIC"
  expiration_time: 168          # 过期时间 （h）

# 定义角色和路径权限的映射关系
role-path-permissions:
  permissions:
    ROLE_ADMIN:
      - "/admin/"
      - "/playlist/"
      - "/artist/"
      - "/song/"
      - "/favorite/"
      - "/comment/"
      - "/banner/"
      - "/feedback/"
    ROLE_USER:
      - "/user/"
      - "/playlist/"
      - "/artist/"
      - "/song/"
      - "/favorite/"
      - "/comment/"
      - "/banner/"
      - "/feedback/"


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kay.music.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn