server:
  port: 8081

spring:
  profiles:
    active: local  # 默认使用 local 配置，可改为 dev 或其他环境
  
  servlet:
    multipart:
      max-file-size: 100MB # 设置最大上传文件大小为100MB
      max-request-size: 1024MB # 设置最大请求大小为1024MB

  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


# 配置 mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
    map-underscore-to-camel-case: true # 类属性与表字段的驼峰映射
  global-config:
    db-config: # 数据库配置
      table-prefix: tb_  # 表名前缀为tb_，表名为前缀连接类名（小写）

jwt:
  expiration_time: 168          # 过期时间 （h）

# 定义角色和路径权限的映射关系
role-path-permissions:
  permissions:
    ROLE_ADMIN:
      - "/admin/"
      - "/playlist/"
      - "/artist/"
      - "/song/"
      - "/favorite/"
      - "/comment/"
      - "/banner/"
      - "/feedback/"
      - "/playlist-binding/"
      - "/playlist/"
    ROLE_USER:
      - "/user/"
      - "/playlist/"
      - "/artist/"
      - "/song/"
      - "/favorite/"
      - "/comment/"
      - "/banner/"
      - "/feedback/"
      - "/playlist-binding/"
      - "/playlist/"


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kay.music.controller
    - group: 'admin'
      paths-to-match: '/admin/**'
      packages-to-scan: com.kay.music.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn